import { Baby, GraduationCap, Mail, Plug, ShieldCheck, TestTube2 } from "lucide-react";
import Image from "next/image";

import { useFamily } from "./FamilyProvider";
import styles from "./AppHeader.module.css";

export function AppHeader({ educationOpen, incomingOpen, pluginsOpen, securityAlertCount, securityOpen, simulatorOpen, onChildrenOpen, onEducationOpen, onIncomingOpen, onProfileOpen, onPluginsOpen, onSecurityOpen, onSimulatorOpen }: { educationOpen: boolean; incomingOpen: boolean; pluginsOpen: boolean; securityAlertCount: number; securityOpen: boolean; simulatorOpen: boolean; onChildrenOpen: () => void; onEducationOpen: () => void; onIncomingOpen: () => void; onProfileOpen: () => void; onPluginsOpen: () => void; onSecurityOpen: () => void; onSimulatorOpen: () => void }) {
  const { family: { parent } } = useFamily();
  return <header className={styles.header}><button aria-label={`Open ${parent.name}'s profile`} className={styles.greeting} onClick={onProfileOpen} type="button"><Image src="/sarah-profile.png" alt={parent.name} width={44} height={44} priority /><span>Hi, {parent.name}</span></button><nav className={styles.actions} aria-label="Family controls"><button aria-label="Child Management" onClick={onChildrenOpen} title="Child Management" type="button"><Baby aria-hidden="true" /></button><button aria-expanded={pluginsOpen} onClick={onPluginsOpen} type="button" aria-label="Connections" title="Connections"><Plug aria-hidden="true" /></button><button aria-expanded={incomingOpen} aria-label="Incoming" onClick={onIncomingOpen} title="Incoming" type="button"><Mail aria-hidden="true" /></button><button aria-expanded={educationOpen} aria-label="Education" onClick={onEducationOpen} title="Education" type="button"><GraduationCap aria-hidden="true" /></button><button aria-expanded={securityOpen} aria-label={`Security${securityAlertCount ? `, ${securityAlertCount} active ${securityAlertCount === 1 ? "alert" : "alerts"}` : ""}`} onClick={onSecurityOpen} title="Security" type="button"><ShieldCheck aria-hidden="true" />{securityAlertCount ? <i /> : null}</button><button aria-expanded={simulatorOpen} aria-label="Simulator" onClick={onSimulatorOpen} title="Simulator" type="button"><TestTube2 aria-hidden="true" /></button></nav></header>;
}
