BUILTIN_SKILLS: tuple[dict[str, object], ...] = (
    {"slug": "school-notice-follow-through", "name": "School Notice Follow-through", "description": "Turn a school message or document into verified family actions.", "instructions": "Identify the child and source. Extract every date, requirement, cost, consent item, and pickup change. Check calendar conflicts, prepare required lists or forms, and ask before consent, payment, or sending a message.", "required_plugin_ids": ["google-workspace"]},
    {"slug": "family-schedule-coordination", "name": "Family Schedule Coordination", "description": "Coordinate appointments, school, activities, and caregivers.", "instructions": "Resolve the people, place, start time, travel time, and responsible caregiver. Check conflicts before creating or changing events. Ask before a meaningful schedule change.", "required_plugin_ids": ["google-workspace", "google-maps"]},
    {"slug": "household-task-management", "name": "Household Task Management", "description": "Create and maintain bounded household work.", "instructions": "Use one clear owner, due condition, and completion test. Update the existing task when it already represents the same outcome. Never duplicate a recurring responsibility.", "required_plugin_ids": ["todoist"]},
    {"slug": "grocery-preparation", "name": "Grocery Preparation", "description": "Prepare grocery lists using family needs and preferences.", "instructions": "Respect allergies, quantities, preferences, and what the family already has. Create a reviewable shopping list. Ask before purchase or substitution with dietary consequences.", "required_plugin_ids": ["instacart"]},
    {"slug": "care-plan-follow-through", "name": "Care Plan Follow-through", "description": "Organize approved care instructions and follow-ups.", "instructions": "Preserve the clinician's wording, medication identity, schedule, and responsible child. Do not diagnose or alter treatment. Escalate contradictions and ask before health judgments.", "required_plugin_ids": ["mychart", "google-workspace"]},
    {"slug": "family-document-processing", "name": "Family Document Processing", "description": "Extract and organize actionable information from family documents.", "instructions": "Keep the original source linked to every extracted fact. Distinguish confirmed text from uncertain interpretation and request clarification when identity, date, or consequence is unclear.", "required_plugin_ids": ["google-workspace"]},
    {"slug": "web-workflow", "name": "Web Workflow", "description": "Complete a bounded workflow in a managed browser.", "instructions": "Inspect before acting, preserve the session identity, and verify every consequential transition. Stop at payment, consent, medical judgment, or an irreversible submission until Mom approves.", "required_plugin_ids": ["agentcore-browser"]},
)
