BUILTIN_SKILLS: tuple[dict[str, object], ...] = (
    {"slug": "incoming-information-routing", "name": "Incoming Information Routing", "description": "Decide what newly received family information changes.", "instructions": "Treat incoming information as evidence, not automatically as work. Resolve it against known family members and existing goals. Record it when no action is needed, resume matching work when it changes an existing outcome, create work only for a concrete new outcome, and ask Mom when identity, intent, conflict, consent, money, medical judgment, an important message, or a consequential schedule change cannot be handled safely.", "required_plugin_ids": []},
    {"slug": "family-security-monitoring", "name": "Family Safety Monitoring", "description": "Review family information against the parent's safety preferences.", "instructions": "Assess the evidence in context rather than matching keywords. Consider credible risks involving privacy, identity, account access, unsafe contact, location exposure, fraud, coercion, or immediate physical safety. Follow the family's saved alert level and instructions. Stay quiet when there is no credible concern. Preserve uncertainty, never invent a threat, and make an alert specific enough for Mom to decide what to do next.", "required_plugin_ids": []},
    {"slug": "education-snapshot-maintenance", "name": "Education Snapshot Maintenance", "description": "Keep each child's education picture current from confirmed evidence.", "instructions": "Use natural language to preserve what the child is learning, how things appear to be going, meaningful changes, and anything important for Mom to know. Keep still-relevant context when new information arrives. Do not infer a curriculum, grade, ability, diagnosis, attendance, deadline, or result that the source does not establish. Ignore information that does not improve an education snapshot.", "required_plugin_ids": []},
    {"slug": "school-notice-follow-through", "name": "School Notice Follow-through", "description": "Turn a school message or document into verified family actions.", "instructions": "Identify the child and source. Extract every date, requirement, cost, consent item, and pickup change. Check calendar conflicts and complete the requested follow-through. Ask only when consent, payment, recipient, or another necessary detail is not already supplied by Mom's request.", "required_plugin_ids": ["google-workspace"]},
    {"slug": "family-schedule-coordination", "name": "Family Schedule Coordination", "description": "Coordinate appointments, school, activities, and caregivers.", "instructions": "Resolve the people, place, start time, travel time, and responsible caregiver. Check conflicts before creating or changing events. Apply the family's saved Calendar reminder preference to new events. Treat Mom's requested calendar action as authorized; ask only when a necessary scheduling choice is missing or ambiguous.", "required_plugin_ids": ["google-workspace", "google-maps"]},
    {"slug": "household-task-management", "name": "Household Task Management", "description": "Create and maintain bounded household work.", "instructions": "Use one clear owner, due condition, and completion test. Update the existing task when it already represents the same outcome. Never duplicate a recurring responsibility.", "required_plugin_ids": ["todoist"]},
    {"slug": "grocery-preparation", "name": "Grocery Preparation", "description": "Prepare grocery lists using family needs and preferences.", "instructions": "Respect allergies, quantities, preferences, and what the family already has. Create a reviewable shopping list. Mom's requested purchase or substitution is authorized; ask only when a necessary quantity, product choice, or dietary consequence is missing or ambiguous.", "required_plugin_ids": ["instacart"]},
    {"slug": "care-plan-follow-through", "name": "Care Plan Follow-through", "description": "Organize approved care instructions and follow-ups.", "instructions": "Preserve the clinician's wording, medication identity, schedule, and responsible child. Do not diagnose or alter treatment. Escalate contradictions and ask before health judgments.", "required_plugin_ids": ["google-workspace"]},
    {"slug": "health-snapshot-review", "name": "Health Snapshot Review", "description": "Summarize a child's authorized health and activity data.", "instructions": "Read only the requested child and date range. Report observed activity, sleep, heart-rate, energy, and distance data in plain language when available. Preserve units and source. Do not diagnose, infer illness, set targets, or alter clinical instructions. Ask only when the child or date range is missing.", "required_plugin_ids": ["apple-health"]},
    {"slug": "family-document-processing", "name": "Family Document Processing", "description": "Extract and organize actionable information from family documents.", "instructions": "Keep the original source linked to every extracted fact. Distinguish confirmed text from uncertain interpretation and request clarification when identity, date, or consequence is unclear.", "required_plugin_ids": ["google-workspace"]},
    {"slug": "web-workflow", "name": "Web Workflow", "description": "Complete a bounded workflow in a managed browser.", "instructions": "Inspect before acting, preserve the session identity, and verify every consequential transition. Mom's requested action is authorized. Ask only when a necessary payment amount, consent choice, medical judgment, or irreversible target is missing or ambiguous.", "required_plugin_ids": ["agentcore-browser"]},
)
